Configuring the anax-build-pipeline
lf-edge/ci-management pull request #11
Opened 2021-04-23 20:11 UTC by Al-tekreeti

Signed-off-by: Mustafa <mmaj1976@gmail.com>

2021-04-26 13:56 UTC, Al-tekreeti commented
Please can you share your feedback regarding this PR?

2021-05-12 18:43 UTC, MightyNerdEric requested changes

2021-05-12 18:43 UTC, MightyNerdEric commented on jjb/ci-management/ci-management.yaml
> +      - '{project-name}-github-packer-jobs':
Please remove these changes from your repo.

2021-05-12 21:39 UTC, MightyNerdEric commented
Replaced by #12. Closing.

2021-05-12 21:39 UTC, closed without merging